const assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.TEST_URL||'http://127.0.0.1:8877/');await p.getByText('已读取 0个运行').waitFor();
 async function start(kind){await p.evaluate(async kind=>{const {fixture}=await import('./src/testing/test_cases.js'),{newRun}=await import('./src/testing/run.js'),{saveWorkspace}=await import('./src/testing/feedback_store.js'),{queuePlayerEvent}=await import('./src/systems/player_decisions.js'),{eventFor}=await import('./src/systems/events.js');const s=fixture({case_id:'PLAYER-EDU-01',seed:73,resources:kind==='blocked'?0:1000});if(kind==='conflict'){s.player_decision_events=[];const cid=s.test.child_id;s.characters[cid].life_goal='家庭生活';s.households[s.characters[cid].current_household_id].responsibilities[cid]={type:'care',mandatory:true,target_id:s.test.mother_id,until:s.current_world_month+36};queuePlayerEvent(s,'relocation',cid,{event:eventFor(s,'relocation')});}const r=newRun(s);await saveWorkspace({runs:[r],active_run:r.run_id,feedback:[]});},kind);await p.reload();await p.locator('#choice-dialog[open]').waitFor();}
 for(const width of [375,390,430]){
  await p.setViewportSize({width,height:844});await start('normal');await p.locator('#choice-dialog [data-player-option="support"]').click();await p.waitForFunction(()=>!document.querySelector('#choice-dialog').open);await p.locator('.timeline-node>summary').first().click();const text=await p.locator('.timeline-node').first().innerText();assert(text.includes('没有强烈反对'));assert(text.includes('长期教育'));assert(!text.includes('未修正'));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  const result=await p.evaluate(async()=>{const {readWorkspace}=await import('./src/testing/feedback_store.js');return (await readWorkspace()).runs[0].state.history.at(-1).result;});assert.equal(result.decision.sampling.method,'player_direct');assert(result.decision_reasons.length);
  await start('blocked');assert(await p.locator('#choice-dialog [data-player-option="support"]').isDisabled());assert((await p.locator('#choice-dialog').innerText()).includes('无法执行：家庭资金不足'));
  await start('conflict');await p.locator('#choice-dialog [data-player-option="support"]').click();await p.getByText('明确冲突：',{exact:false}).first().waitFor();assert((await p.locator('#choice-dialog').innerText()).includes('照护'));assert(await p.locator('#auto').isDisabled());await p.locator('#choice-dialog [data-player-option="respect"]').click();await p.waitForFunction(()=>!document.querySelector('#choice-dialog').open);console.log('authority mobile',width,'passed');
 }
 // A quiet run still groups ordinary months; the richer 66-month fixture can legitimately contain only meaningful nodes.
 const grouped=await p.evaluate(async()=>{const {fixture}=await import('./src/testing/test_cases.js'),{defaults}=await import('./src/config/mock_tunables.js'),{month}=await import('./src/core/simulation.js'),{timelineView}=await import('./src/ui/compact_views.js');const s=fixture({config:{...defaults(),content_enabled:false,background_event_frequency:0,decision_event_frequency:0,marriage_opportunity_frequency:0,reproduction_frequency:0,illness_frequency:0}});for(let i=0;i<3;i++)month(s);return timelineView(s,s.history,0,()=>'',()=> '日常');});assert(grouped.includes('month-run'));
 assert.deepEqual(errors,[]);console.log('PASS: direct player result, explicit blocked reasons, conflict followup, compact grouping, no errors');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
