// Explicit test-player policies below are only test inputs; the application never supplies them.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
vm.runInThisContext(['worlds.js','src/core/legacy_bridge.js','decisions.js'].map(f=>fs.readFileSync(path.join(root,f),'utf8')).join('\n'));
(async()=>{
 const {fixture}=await import('../src/testing/test_cases.js'),{defaults}=await import('../src/config/mock_tunables.js');
 const {month,command,executeDecision}=await import('../src/core/simulation.js'),{newRun,step,replay}=await import('../src/testing/run.js');
 const {eventFor,backgroundCandidates}=await import('../src/systems/events.js'),{resolveDecision,decide}=await import('../src/systems/behavior.js');
 const {lifeContext,startAway}=await import('../src/systems/life_context.js'),{defaultBehaviors}=await import('../src/systems/default_behavior.js');
 const {updateLongTerms}=await import('../src/systems/long_term_state.js'),{updateSituations}=await import('../src/systems/ongoing_situations.js');
 const {pendingDecision,queuePlayerEvent,playerChoices,openPlayerWindow,needsPlayer}=await import('../src/systems/player_decisions.js');
 const {ensureMarriageCandidates,arrangeMarriage,establishMarriage,currentMarriage}=await import('../src/systems/marriage.js');
 const {reproductionConditions,startReproduction}=await import('../src/systems/reproduction.js');
 const {die}=await import('../src/systems/death.js'),{feedbackFor,exportEnvelope,validateImport}=await import('../src/testing/feedback_store.js');
 const {completeEvent}=await import('../src/systems/action_catalog.js');
 const report={tests:[],runs:[]};const check=(label,fn)=>{fn();report.tests.push(label);};
 const quiet=()=>fixture({seed:9,config:{...defaults(),decision_event_frequency:0,marriage_opportunity_frequency:0,reproduction_frequency:0,illness_frequency:0,aging_loss:0}});
 const chooseAll=(s,apply=cmd=>command(s,cmd))=>{let count=0;for(let p;(p=pendingDecision(s));){assert(++count<60,'bounded pending queue');const opts=playerChoices(s,p).filter(o=>o.feasible);const chosen=(p.type==='relocation'?opts.find(o=>o.id==='skip'):null)||opts.find(o=>o.id==='support'||o.id==='force'||o.target_id)||opts.find(o=>!['skip','respect'].includes(o.id))||opts[0];apply({type:'player_choice',event_id:p.id,option_id:chosen.id});}return count;};
 let s=quiet(),cid=s.test.child_id;
 check('TEST-DECISION-TERMINAL-01',()=>{for(const type of ['learning','education','career','relocation','away_review','marriage','birth','music','safety','health','conflict','strain']){const e=eventFor(s,type,s.test.target_id);assert(e.decision_goal);assert(e.terminal_outcomes.length>=2);assert(e.mock_actions.some(a=>a.conditions.action_type==='terminal_action'));}assert(eventFor(s,'learning').mock_actions.some(a=>a.id==='try_lesson'));});
 check('TEST-DECISION-MULTISTAGE-01',()=>{
  const e=eventFor(s,'learning'),first=decide(s,cid,e,{noise:false,draw:0}),idx=first.candidate_actions.findIndex(a=>a.action_type==='transition_action');
  const lo=first.candidate_actions.slice(0,idx).reduce((n,a)=>n+a.probability_fraction,0),draw=lo+first.candidate_actions[idx].probability_fraction/2;
  const r=resolveDecision(s,cid,e,{noise:false,draw});assert.equal(r.stages.length,2);assert(r.stages[1].event.context_facts.information_acquired);assert.equal(r.terminal,true);assert.notEqual(r.stages.at(-1).candidate_actions.find(a=>a.action_id===r.chosen_action_id).action_type,'transition_action');
  const accepted=resolveDecision(s,cid,e,{noise:false,draw:0});executeDecision(s,cid,accepted);assert(lifeContext(s,cid).terms.some(t=>t.type==='short_trial'));const old=s.characters[cid].skills.length;month(s);assert(s.characters[cid].skills.length>old);chooseAll(s);
 });
 s=quiet();cid=s.test.child_id;s.households[s.characters[cid].current_household_id].responsibilities[cid]={type:'care',until:s.current_world_month+48};
 check('TEST-CLOSURE-AWAY-01',()=>{const d=resolveDecision(s,cid,eventFor(s,'relocation'),{noise:false,draw:0});assert.equal(d.chosen_action_id,'commit_terms');executeDecision(s,cid,d);const ctx=lifeContext(s,cid);assert(!ctx.co_resident);assert.equal(ctx.care_time,0);assert(ctx.away.family_responsibility_changes.length);assert(defaultBehaviors(s,cid).primary.name.includes('外地'));const pools=backgroundCandidates(s,cid);assert(!pools.some(e=>e.id==='family'));assert(pools.some(e=>e.id==='away_work'));for(let i=0;i<12;i++){chooseAll(s);month(s);}assert(lifeContext(s,cid).away);assert(s.history.at(-1).resource_changes.some(x=>x.income>0));});
 check('TEST-CLOSURE-AWAY-36M',()=>{for(let i=12;i<36;i++){chooseAll(s);month(s);}assert(lifeContext(s,cid).away.due_decision);assert(s.player_decision_events.some(e=>e.type==='away_review'));chooseAll(s);assert(!lifeContext(s,cid).away?.due_decision);});
 s=quiet();cid=s.test.child_id;
 check('TEST-SITUATION-FAMILY-01',()=>{for(let i=0;i<12;i++){s.current_world_month++;updateSituations(s,cid,{conflict:true});}const xs=Object.values(s.ongoing_situations).filter(x=>x.type==='family_conflict');assert.equal(xs.length,1);assert(xs[0].needs_decision);assert(xs[0].development_history.some(x=>x.kind==='worsened'));for(let i=0;i<10;i++){s.current_world_month++;updateSituations(s,cid,{conflict:false});}assert.equal(xs[0].status,'resolved');s.current_world_month++;updateSituations(s,cid,{conflict:true});const next=Object.values(s.ongoing_situations).at(-1);assert(next.previous_situation_ids.includes(xs[0].id));});
 check('TEST-SITUATION-FAMILY-MONTHLY',()=>{const r=newRun(quiet()),s=r.state,cid=s.test.child_id;command(s,{type:'enroll'});for(let i=0;i<12;i++){while(pendingDecision(s)){const e=pendingDecision(s),option=playerChoices(s,e).find(o=>o.id==='reduce')||playerChoices(s,e).find(o=>o.feasible);command(s,{type:'player_choice',event_id:e.id,option_id:option.id});}if(i===6){openPlayerWindow(s,'care',cid);const e=pendingDecision(s);command(s,{type:'player_choice',event_id:e.id,option_id:'reduce'});}month(s);}const issues=Object.values(s.ongoing_situations).filter(x=>x.type==='family_conflict'&&x.participants.includes(cid));assert.equal(issues.length,1);assert.equal(issues[0].status,'resolved');assert(s.careers[cid].time+s.education[cid].time<=1);});
 check('TEST-EVENT-HISTORY-01',()=>assert(s.recent_history[cid].some(x=>x.phase==='resolved')));
 s=quiet();cid=s.test.child_id;
 check('TEST-MARRIAGE-NPC-01',()=>{const people=ensureMarriageCandidates(s,cid);assert(people.length>=2);const target=people[0].character_id;const e=eventFor(s,'marriage',target);const previous={child:resolveDecision(s,cid,e,{noise:false,draw:.999999}),other:resolveDecision(s,target,{...e,target_id:cid},{noise:false,draw:.999999}),family:resolveDecision(s,target,{...e,target_id:cid},{noise:false,draw:.999999})};const r=arrangeMarriage(s,cid,target,'ordinary',null,previous);assert.equal(r.status,'other_refused');assert(s.marriage_proposal_history.some(x=>x.candidate_character_id===target));for(let i=0;i<12;i++){chooseAll(s);month(s);}assert(s.characters[target]);assert(s.characters[target].active_simulation);});
 check('TEST-MARRIAGE-NPC-02',()=>{const target=s.test.target_id,other=ensureMarriageCandidates(s,target).find(x=>x.character_id!==cid&&!currentMarriage(s,x.character_id));assert(other);establishMarriage(s,target,other.character_id);month(s);assert(currentMarriage(s,target));});
 s=quiet();cid=s.test.child_id;
 check('TEST-MARRIAGE-NPC-03',()=>{establishMarriage(s,cid,s.test.target_id);assert.equal(s.characters[cid].spouse_character_id,s.test.target_id);assert.equal(s.characters[s.test.target_id].spouse_character_id,cid);assert.equal(s.characters[cid].marriage_id,s.characters[s.test.target_id].marriage_id);assert.equal(reproductionConditions(s,cid,s.test.target_id),null);startReproduction(s,cid,s.test.target_id);for(let i=0;i<9;i++){chooseAll(s);month(s);}const baby=Object.values(s.characters).find(c=>c.biological_parent_ids.includes(cid));assert(baby.biological_parent_ids.includes(s.test.target_id));});
 for(const [caseId,type] of [['PLAYER-RESOURCE-01','resource'],['PLAYER-EDU-01','education'],['PLAYER-CAREER-01','relocation'],['PLAYER-MARRIAGE-01','marriage'],['PLAYER-FORCE-01','force']]){
  check(caseId,()=>{const s=fixture({seed:0,case_id:caseId}),p=pendingDecision(s);assert.equal(p.type,type);const before=JSON.stringify(s);assert.throws(()=>month(s),/需要你的决定/);assert.equal(JSON.stringify(s),before);const opts=playerChoices(s,p);if(type==='marriage')assert(opts.filter(x=>x.target_id).length>=2);const o=opts.find(x=>x.feasible&&x.id!=='skip'&&x.id!=='respect');command(s,{type:'player_choice',event_id:p.id,option_id:o.id});assert(s.history.at(-1).result.player_choice);assert.equal(s.history.at(-1).kind,'player_choice');});
 }
 for(const caseId of ['PLAYER-HEIR-01','PLAYER-SUCCESSION-01'])check(caseId,()=>{const s=fixture({case_id:caseId});command(s,{type:'death'});assert.equal(pendingDecision(s).type,'succession');chooseAll(s);assert(s.control.current_control_character_id);assert(Object.values(s.inheritances).some(x=>x.status==='completed'));});
 check('PLAYER-INCOMING-MARRIAGE',()=>{const s=quiet(),cid=s.test.child_id,target=s.test.target_id;assert(needsPlayer(s,target,eventFor(s,'marriage',cid)));const e=pendingDecision(s);assert.equal(e.character_id,cid);assert.equal(e.payload.event.target_id,target);assert(!currentMarriage(s,cid));assert.throws(()=>month(s),/需要你的决定/);});
 check('PLAYER-WINDOW-03M',()=>{const s=quiet();assert.throws(()=>openPlayerWindow(s,'education',s.test.child_id));for(let i=0;i<3;i++)month(s);openPlayerWindow(s,'education',s.test.child_id);assert(pendingDecision(s));assert.throws(()=>month(s));});
 check('FORCE-HARD-LIMIT',()=>{const s=fixture({case_id:'PLAYER-FORCE-01'}),p=pendingDecision(s);s.resources.households[s.characters[p.character_id].current_household_id].household_resources=0;assert.throws(()=>command(s,{type:'player_choice',event_id:p.id,option_id:'force'}),/无法执行/);assert(!s.careers[p.character_id]);assert.equal(s.player.force_credits,1);});
 check('PLAYER-REPLAY-FEEDBACK',()=>{const r=newRun(fixture({case_id:'PLAYER-EDU-01',seed:0}));chooseAll(r.state,cmd=>step(r,cmd));const f=feedbackFor(r,0,'合理');assert.equal(f.scene.kind,'player_choice');assert.doesNotThrow(()=>validateImport(exportEnvelope({feedback:[f],runs:[r]})));const expected=structuredClone(r.state);expected.history.forEach(e=>delete e.command_index);assert.deepEqual(replay(r),expected);});
 check('GOAL-GATING-PRESERVED',()=>{const s=quiet(),cid=s.test.child_id;s.characters[cid].life_goal='家庭生活';assert(decide(s,cid,eventFor(s,'learning'),{noise:false}).candidate_actions.every(a=>a.modifiers.life_goal===0));s.characters[cid].life_goal='职业成就';assert(decide(s,cid,eventFor(s,'career'),{noise:false}).candidate_actions.find(a=>a.action_id==='commit_terms').modifiers.life_goal>0);});
 check('CHILD-FUNDED-EDUCATION',()=>{const s=quiet(),cid=s.test.child_id;s.characters[cid].birth_month=s.current_world_month-14*12;if(s.careers[cid])s.careers[cid].status='ended';const r=resolveDecision(s,cid,eventFor(s,'education'),{noise:false,draw:0});assert.equal(r.chosen_action_id,'commit_terms');executeDecision(s,cid,r);assert.equal(s.education[cid].status,'active');});
 check('PLAYER-CHOICE-ACTUAL-EFFECT',()=>{const s=fixture({case_id:'PLAYER-FORCE-01',seed:0}),cid=s.test.child_id,p=pendingDecision(s),oldStress=s.characters[cid].dynamic.stress;command(s,{type:'player_choice',event_id:p.id,option_id:'force'});assert.equal(s.careers[cid].status,'active');assert(s.characters[cid].dynamic.stress>oldStress);assert.equal(s.player.force_credits,0);assert(s.history.at(-1).result.decision.prior_refusal);});
 check('MIXED-VERSION-ARCHIVE',()=>{const run=newRun(quiet()),old=structuredClone(run);old.mock_version='2.0.0-alpha';old.schema_version=2;delete old.state.config.event_cooldown;delete old.initial_state.config.event_cooldown;assert.doesNotThrow(()=>validateImport(exportEnvelope({feedback:[],runs:[old,run]})));assert.throws(()=>step(old,{type:'month'}),/旧版本存档/);});
 for(const months of [120,360]){
  const r=newRun(fixture({seed:31,world:'ancient',case_id:'TC-EDU-01'}),'life'),s=r.state;let playerCount=0,pausedMonths=new Set(),seen=new Set(Object.keys(s.characters)),lastBackground={},violations=0;
  const targetMonth=s.current_world_month+months;for(let i=0;s.current_world_month<targetMonth;i++){
   if(pendingDecision(s)){pausedMonths.add(i);playerCount+=chooseAll(s,cmd=>step(r,cmd));}
   if(!s.control.current_control_character_id)break;
   const log=step(r,{type:'month'});
   for(const c of Object.values(s.characters)){assert(!seen.has(c.character_id)||s.characters[c.character_id]);seen.add(c.character_id);if(!c.alive)assert.equal(c.active_simulation,false);const m=currentMarriage(s,c.character_id);for(const t of Object.values(s.long_term_states).filter(t=>t.character_id===c.character_id&&t.status==='active')){assert(c.alive);if(t.source)assert.equal(s[t.source.system][t.source.id].status,'active');}if(m){assert.equal(c.spouse_character_id,m.people.find(x=>x!==c.character_id));assert.equal(c.marriage_id,m.id);}}
   for(const rep of log.reports){const e=rep.background?.event;if(e){const key=rep.character_id+':'+e.id;if(lastBackground[key]&&log.month-lastBackground[key]<s.config.background_cooldown)violations++;lastBackground[key]=log.month;}}
  }
  playerCount+=chooseAll(s,cmd=>step(r,cmd));assert.equal(violations,0);assert(playerCount>0);assert(pausedMonths.size<months*.6,'not interrupted every month');
  const stats={seed:31,months,people:Object.keys(s.characters).length,births:Object.values(s.reproduction).filter(x=>x.status==='completed').length,marriages:Object.keys(s.marriages).length,newMarriages:Object.keys(s.marriages).length-1,educationChanges:s.history.filter(h=>h.kind==='month').flatMap(h=>h.reports).filter(r=>r.diff?.some(d=>d.path.startsWith('education'))).length,decisions:s.history.flatMap(h=>h.reports||[]).filter(r=>r.decision).length,playerDecisions:playerCount,pausedMonths:pausedMonths.size,ongoingSituations:Object.keys(s.ongoing_situations).length,longTermStates:Object.keys(s.long_term_states).length,backgroundRepeatViolations:violations,householdResources:Object.values(s.resources.households).map(x=>Math.round(x.household_resources))};
  report.runs.push(stats);if(months===120){const expected=structuredClone(s);expected.history.forEach(e=>delete e.command_index);assert.deepEqual(replay(r),expected);}
 }
 report.tests.push('TEST-EVENT-REPETITION-01','ANCIENT-LIFE-10Y','ANCIENT-LIFE-30Y');console.log(JSON.stringify(report,null,2));if(process.env.WRITE_V230_REPORT==='1')fs.writeFileSync(path.join(root,'reports/v230-regression.json'),JSON.stringify(report,null,2)+'\n');
})().catch(e=>{console.error(e);process.exitCode=1;});
