const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');process.chdir(path.resolve(__dirname,'..'));
vm.runInThisContext(['worlds.js','src/core/legacy_bridge.js','decisions.js'].map(f=>fs.readFileSync(f,'utf8')).join('\n'));
(async()=>{
 const {fixture}=await import('../src/testing/test_cases.js'),{createCharacter}=await import('../src/systems/character_generation.js'),{createHousehold}=await import('../src/systems/household.js'),{createState}=await import('../src/core/state.js'),{defaults,META}=await import('../src/config/mock_tunables.js');
 const {newRun,step,replay}=await import('../src/testing/run.js'),{month,command}=await import('../src/core/simulation.js'),{pendingDecision,playerChoices,queuePlayerEvent}=await import('../src/systems/player_decisions.js');
 const {initializePopulation,populationStats,selectNPC,recordNPCExposure,importantNPC}=await import('../src/systems/npc_world.js'),{SURNAMES,MALE_PARTS,FEMALE_PARTS,NEUTRAL_PARTS}=await import('../src/config/mock_names.js');
 const {ANCIENT_EVENTS}=await import('../src/content/ancient_events.js'),{instantiateContent,applyRoutineContent}=await import('../src/content/event_runtime.js'),{ROUTINE_IDS}=await import('../src/content/decision_audit.js');
 const {establishMarriage,eligibleMarriageCandidatePool,marriageResponse}=await import('../src/systems/marriage.js'),{eventFor}=await import('../src/systems/events.js'),{resolveDecision,chosen,preparePlayerDecision}=await import('../src/systems/behavior.js');
 const {reproductionConditions,conceptionChance,checkConception,startReproduction,updateReproduction,fertilityCapacity}=await import('../src/systems/reproduction.js'),{addLongTerm}=await import('../src/systems/long_term_state.js');
 const report={version:META.mock_version,tests:[],statistics:{}};const ok=(id,fn)=>{fn();report.tests.push(id);};
 const quiet=()=>{const s=fixture({seed:29});Object.assign(s.config,{content_enabled:false,decision_event_frequency:0,background_event_frequency:0,illness_frequency:0,marriage_opportunity_frequency:0,reproduction_frequency:0});return s;};
 const answer=s=>{let guard=0;while(pendingDecision(s)){assert(++guard<100);const p=pendingDecision(s),opts=playerChoices(s,p).filter(o=>o.feasible),o=opts.find(o=>['skip','respect'].includes(o.id))||opts[0];command(s,{type:'player_choice',event_id:p.id,option_id:o.id});}};
 let s=quiet(),a=s.test.child_id,b=s.test.target_id;establishMarriage(s,a,b);const baby=createCharacter(s,{parents:[b,a],household_id:s.characters[a].current_household_id,age_years:1});s.households[s.characters[a].current_household_id].responsibilities[a]={type:'care',until:s.current_world_month+36};addLongTerm(s,a,'short_trial',null,2,50,[]);s.health[a].value=80;
 const before=s.careers[a].progress,log=month(s),r=log.reports.find(r=>r.character_id===a);
 ok('TEST-MONTH-MULTITRACK-01',()=>{assert(s.careers[a].progress>before);for(const k of['career','family','care','health','resources','relationships','parenting','long_term'])assert(r.routine.tracks[k],k);assert(s.health[a].value>80);});
 s=quiet();const initial=s.current_world_month;s.month_queue={month:initial,items:[{cid:s.test.child_id,event:eventFor(s,'education')},{cid:s.test.child_id,event:eventFor(s,'safety')},{cid:s.test.child_id,event:eventFor(s,'music')}]};const run=newRun(s);let part=step(run,{type:'month'});
 ok('TEST-MONTH-MULTIEVENT-01',()=>{assert(pendingDecision(s));assert.equal(s.month_queue.items.length,2);assert.equal(s.current_world_month,initial);assert.throws(()=>month(s),/需要你的决定/);});
 step(run,{type:'player_choice',event_id:pendingDecision(s).id,option_id:'skip'});part=step(run,{type:'month'});assert.equal(s.current_world_month,initial);assert.equal(part.reports[0].special_events.length,2);assert.equal(s.month_queue.items.length,0);const expected=structuredClone(s);expected.history.forEach(e=>delete e.command_index);assert.deepEqual(replay(run),expected);
 s=quiet();Object.assign(s.config,{decision_event_frequency:1,marriage_opportunity_frequency:1,special_attempts:2});const naturalBefore=s.current_world_month,natural=month(s);assert(pendingDecision(s));assert(natural.reports.some(r=>r.routine?.tracks.career));assert(s.month_queue.items.length>=2);while(s.month_queue.items.length){answer(s);month(s);}assert.equal(s.current_world_month,naturalBefore+1);report.tests.push('TEST-MONTH-MULTIEVENT-NATURAL: routine plus independently triggered queue, same month after choices');
 s=quiet();const t=ANCIENT_EVENTS.find(t=>t.event_id==='parents-1'),event=instantiateContent(s,s.test.child_id,t);const routine=applyRoutineContent(s,s.test.child_id,event);
 ok('TEST-EVENT-DECISION-AUDIT-01',()=>{assert.equal(ANCIENT_EVENTS.length,104);assert.equal(routine.kind,'ROUTINE_MONTHLY_PROGRESS');assert.equal(routine.candidate_actions.length,0);for(const t of ANCIENT_EVENTS){assert(t.decision_audit.reason);if(ROUTINE_IDS.has(t.event_id))assert.equal(t.flow_type,'ROUTINE_MONTHLY_PROGRESS');}});report.statistics.audit={reviewed:104,routine:ROUTINE_IDS.size,decisions:104-ROUTINE_IDS.size};
 const riskStats=[];for(const risk of[10,90]){const s=quiet(),cid=s.test.child_id,c=s.characters[cid];for(const k of Object.keys(c.personality))c.personality[k]=50;c.personality.risk_orientation=risk;c.interests=[{name:'手工',intensity:90}];c.life_goal='职业成就';if(s.careers[cid])s.careers[cid].status='ended';const event={...eventFor(s,'career'),conditions:{contract_terms_known:true,information_verified:false}},counts={accept:0,inquire:0,defer:0,reject:0};for(let i=0;i<10000;i++){const d=resolveDecision(s,cid,event);counts[chosen(d.stages[0]).outcome]++;}riskStats.push({risk_orientation:risk,n:10000,...counts});s.resources.households[c.current_household_id].household_resources=0;assert.throws(()=>preparePlayerDecision(s,cid,event),/无法执行/);}
 console.log('risk',riskStats);ok('TEST-RISK-ORIENTATION-01',()=>{assert(riskStats[0].inquire>riskStats[1].inquire*1.4);assert(riskStats[1].accept>riskStats[0].accept*1.4);});report.statistics.risk=riskStats;
 const matching=[];for(const poor of[false,true]){const s=quiet(),cid=s.test.target_id,target=s.test.child_id;s.characters[cid].mock_marriage_willingness=80;for(const x of Object.values(s.characters))for(const k of Object.keys(x.personality))x.personality[k]=50;if(poor){s.characters[cid].birth_month-=25*12;s.characters[cid].mock_marriage_willingness=10;s.households[s.characters[cid].current_household_id].responsibilities[cid]={type:'care',until:s.current_world_month+24};for(const r of Object.values(s.relationships))if(r.people.includes(cid)&&r.people.includes(target))r.attitude=-40;s.resources.households[s.characters[target].current_household_id].household_resources=150;}
 const event={...eventFor(s,'marriage',target),cost:0},counts={accept:0,defer:0,reject:0};for(let i=0;i<10000;i++){const d=marriageResponse(s,cid,event);counts[chosen(d).outcome]++;assert(d.decision_reasons.length);if(poor&&chosen(d).outcome==='reject')assert(d.decision_reasons.some(x=>x.code!=='low_probability_deviation'));}matching.push({condition:poor?'low_match':'high_match',n:10000,...counts});}
 ok('TEST-MARRIAGE-MATCH-01',()=>assert(matching[0].accept>7000));ok('TEST-MARRIAGE-MATCH-02',()=>assert(matching[1].reject+matching[1].defer>matching[0].reject+matching[0].defer));report.statistics.matching=matching;
 const couple=(count=0,health=95,fertility=80,years=28)=>{const s=quiet(),a=s.test.child_id,b=s.test.target_id;s.config.reproduction_frequency=.025;for(const id of[a,b]){s.characters[id].birth_month=s.current_world_month-years*12;s.health[id].value=95;s.characters[id].physiology.fertility_basis=fertility;}establishMarriage(s,a,b);for(const id of[a,b])s.health[id].value=health;for(let i=0;i<count;i++)createCharacter(s,{parents:[b,a],age_years:4+i,household_id:s.characters[a].current_household_id});return s;};
 const trials=(s,n=5000)=>{const a=s.test.child_id,b=s.test.target_id,info=conceptionChance(s,a,b);let count=0;for(let i=0;i<n;i++){const r=checkConception(s,a,b);if(r.started){count++;delete s.reproduction[r.id];for(const [id,t]of Object.entries(s.long_term_states))if(t.source?.id===r.id)delete s.long_term_states[id];s.life_notices.pop();}}return {n,entered:count,frequency:count/n,priority:info.priority.value,capacity:info.capacity.value,chance:info.chance};};
 s=couple();s.characters[s.test.child_id].last_birth_month=s.current_world_month;const date=s.current_world_month;for(let m=1;m<=12;m++){s.current_world_month=date+m;assert.equal(trials(s,1000).entered,0);}s.current_world_month=date+13;
 ok('TEST-REPRO-POSTPARTUM-01',()=>assert.equal(reproductionConditions(s,s.test.child_id,s.test.target_id),null));
 ok('TEST-REPRO-AGE-01',()=>{assert(conceptionChance(couple(0,95,80,44),a,b).chance>0);assert.equal(trials(couple(0,95,80,45)).entered,0);});
 const children=[0,1,2,3,4].map(n=>({children:n,...trials(couple(n))}));ok('TEST-REPRO-CHILDREN-01',()=>{for(let i=1;i<5;i++)assert(children[i].chance<children[i-1].chance);assert(children[3].chance<children[2].chance/2);assert(children[4].entered>0);});report.statistics.children=children;
 const health=[100,70,40,20].map(h=>{const s=couple(0,h);return {health:h,health_factor:fertilityCapacity(s,a,b).health_factor,...trials(s)};});ok('TEST-REPRO-HEALTH-01',()=>{assert(health.every(x=>x.health_factor<=.95));assert.equal(health[3].entered,0);assert(health[0].entered>health[1].entered&&health[1].entered>health[2].entered);});report.statistics.health=health;
 const fertility=[95,55,10].map(f=>({fertility_base:f,...trials(couple(0,95,f))}));ok('TEST-REPRO-FERTILITY-BASE-01',()=>assert(fertility[0].entered>fertility[1].entered&&fertility[1].entered>fertility[2].entered));report.statistics.fertility=fertility;
 s=couple();const start=startReproduction(s,a,b);assert(start.started);assert.equal(checkConception(s,a,b).started,false);s.current_world_month+=9;const born=updateReproduction(s);ok('TEST-PREGNANCY-NOTICE-01',()=>{assert(s.life_notices.some(n=>n.type==='pregnancy'));assert.equal(born.length,1);assert.equal(s.characters[a].last_birth_month,s.current_world_month);assert(s.life_notices.some(n=>n.type==='birth'));});
 s=fixture({seed:4});initializePopulation(s);const stats=populationStats(s);ok('TEST-NPC-POOL-01',()=>{assert.equal(stats.total-1,s.config.npc_initial_population);assert.equal(Object.keys(stats.age_groups).length,6);});report.statistics.initial_population=stats;for(const h of Object.values(s.households)){const given=h.members.map(id=>s.characters[id].given_name);assert.equal(new Set(given).size,given.length,'family given names differ');}
 const estateState=fixture({seed:93});initializePopulation(estateState);const deceased=estateState.test.child_id,heir=createCharacter(estateState,{age_years:20,parents:[estateState.test.target_id,deceased],household_id:createHousehold(estateState,'另居子女')});estateState.resources.personal[deceased].personal_inheritable_estate=42;command(estateState,{type:'death'});command(estateState,{type:'player_choice',event_id:pendingDecision(estateState).id,option_id:heir.character_id});assert.equal(pendingDecision(estateState).type,'inheritance');command(estateState,{type:'player_choice',event_id:pendingDecision(estateState).id,option_id:heir.character_id});assert.equal(estateState.resources.personal[heir.character_id].personal_inheritable_estate,42);report.tests.push('PLAYER-ESTATE-AFTER-CROSS-HOUSEHOLD-SUCCESSION');
 const naming=createState(12,'ancient',defaults()),hid=createHousehold(naming,'姓名测试');for(let i=0;i<300;i++)createCharacter(naming,{household_id:hid,age_years:20});const names=Object.values(naming.characters),unique=new Set(names.map(c=>c.surname+c.given_name));ok('TEST-NAME-DIVERSITY-01',()=>assert(unique.size>=297));report.statistics.names={n:300,duplicates:300-unique.size,surnames_used:new Set(names.map(c=>c.surname)).size,given_names_used:new Set(names.map(c=>c.given_name)).size,pool_sizes:{surnames:SURNAMES.length,male:MALE_PARTS.length,female:FEMALE_PARTS.length,neutral:NEUTRAL_PARTS.length}};
 const pools=Object.values(s.characters).filter(c=>!c.marriage_id&&s.current_world_month-c.birth_month>=18*12&&s.current_world_month-c.birth_month<45*12).map(c=>eligibleMarriageCandidatePool(s,c.character_id));ok('TEST-MARRIAGE-CANDIDATE-DIVERSITY-01',()=>assert(new Set(pools.flat().map(x=>x.character_id)).size>10));report.statistics.candidates={subjects:pools.length,average_pool:pools.reduce((n,p)=>n+p.length,0)/pools.length,unique_candidates:new Set(pools.flat().map(x=>x.character_id)).size};
 console.log(JSON.stringify(report,null,2));fs.writeFileSync('reports/v230-validation.json',JSON.stringify(report,null,2)+'\n');
})().catch(e=>{console.error(e);process.exitCode=1;});
