const assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[],requests=[],rows=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));page.setDefaultTimeout(20000);
 await page.goto(process.env.TEST_URL||'http://127.0.0.1:8877/');await page.getByText('已读取 0个运行').waitFor();await page.locator('nav [data-page="tests"]').click();await page.locator('#new-life').click();
 const initial=await page.evaluate(async()=>{const {readWorkspace}=await import('./src/testing/feedback_store.js');const s=(await readWorkspace()).runs[0].state;return Object.keys(s.characters).length;});assert.equal(initial,97);
 await page.locator('nav [data-page="tests"]').click();await page.locator('#npc-stats summary').click();assert((await page.locator('#npc-stats').innerText()).includes('年龄'));await page.locator('nav [data-page="simulation"]').click();
 async function setup(){return page.evaluate(async()=>{const {fixture}=await import('./src/testing/test_cases.js'),{initializePopulation}=await import('./src/systems/npc_world.js'),{establishMarriage}=await import('./src/systems/marriage.js'),{startReproduction}=await import('./src/systems/reproduction.js'),{newRun,step}=await import('./src/testing/run.js'),{pendingDecision,playerChoices}=await import('./src/systems/player_decisions.js'),{saveWorkspace}=await import('./src/testing/feedback_store.js');
  const s=fixture({seed:733}),a=s.test.child_id,b=s.test.target_id;initializePopulation(s);Object.assign(s.config,{content_enabled:false,decision_event_frequency:0,marriage_opportunity_frequency:0,background_event_frequency:0,reproduction_frequency:0,illness_frequency:0});establishMarriage(s,a,b);const run=newRun(s,'life','mobile-five-years'),end=s.current_world_month+60;
  while(s.current_world_month<end){let p;while((p=pendingDecision(s))){const choices=playerChoices(s,p).filter(x=>x.feasible),o=choices.find(x=>x.id==='skip'||x.id==='respect')||choices[0];step(run,{type:'player_choice',event_id:p.id,option_id:o.id});}step(run,{type:'month'});}
  s.health[a].value=90;const pregnancy=startReproduction(s,a,b);if(!pregnancy.started)throw Error(pregnancy.reason);await saveWorkspace({runs:[run],active_run:run.run_id,feedback:[]});return {month:s.current_world_month,mother:a};
 });}
 for(const width of[375,390,430]){await page.setViewportSize({width,height:844});const before=await setup();await page.reload();await page.locator('.pregnancy-badge').waitFor();assert((await page.locator('#pending').innerText()).includes('【怀孕】'));assert((await page.locator('.pregnancy-badge').innerText()).includes('第1个月'));assert((await page.locator('.pregnancy-badge').innerText()).includes('健康 90'));
  assert(await page.locator('.timeline-year:not([open])').count()>=4);await page.locator('[data-months="1"]').click();await page.waitForFunction(()=>document.querySelector('.pregnancy-badge')?.textContent.includes('第2个月'));if(await page.locator('.timeline-year[open] .month-run:not([open])>summary').count())await page.locator('.timeline-year[open] .month-run:not([open])>summary').first().click();await page.locator('.timeline-year[open] .timeline-node>summary').first().click();assert((await page.locator('.timeline-node').first().innerText()).includes('本月生活'));assert((await page.locator('.timeline-node').first().innerText()).includes('工作：'));
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert(!overflow);const nav=(await page.locator('nav').boundingBox()).height;assert(nav<=60);await page.locator('#summary').scrollIntoViewIfNeeded();fs.mkdirSync('test-results',{recursive:true});await page.screenshot({path:'test-results/v230-'+width+'.png'});
  const saved=await page.evaluate(async()=>{const {readWorkspace}=await import('./src/testing/feedback_store.js');return (await readWorkspace()).runs[0].state.current_world_month;});assert.equal(saved,before.month+1);rows.push({width,overflow,nav_height:nav,months_before_check:60,pregnancy_immediate:true,pregnancy_month_updates:true,multitrack_visible:true});
 }
 await setup();await page.evaluate(async()=>{const {readWorkspace,saveWorkspace}=await import('./src/testing/feedback_store.js'),{queuePlayerEvent}=await import('./src/systems/player_decisions.js'),{eventFor}=await import('./src/systems/events.js');const w=await readWorkspace(),s=w.runs[0].state;queuePlayerEvent(s,'education',s.test.child_id,{event:eventFor(s,'education')});await saveWorkspace(w);});await page.reload();await page.locator('#choice-dialog[open]').waitFor();assert((await page.locator('#choice-dialog').innerText()).includes('【怀孕】'),'pregnancy remains visible alongside player pause');
 assert.deepEqual(errors,[]);assert(requests.every(url=>!url.includes('/api/')));if(!process.env.TEST_URL)fs.writeFileSync('reports/v230-mobile.json',JSON.stringify({url:process.env.TEST_URL||'local static preview',rows,errors,static_only:true},null,2)+'\n');console.log(JSON.stringify(rows));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
