const assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[],requests=[],rows=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));page.setDefaultTimeout(20000);
 await page.goto(process.env.TEST_URL||'http://127.0.0.1:8877/');await page.getByText('已读取 0个运行').waitFor();await page.locator('nav [data-page="tests"]').click();await page.locator('#new-life').click();
 assert.equal(await page.evaluate(async()=>{const {readWorkspace}=await import('./src/testing/feedback_store.js');return (await readWorkspace()).runs[0].mock_version;}),'2.4.0-alpha');
 async function setup(){return page.evaluate(async()=>{
  const {fixture}=await import('./src/testing/test_cases.js'),{initializePopulation}=await import('./src/systems/npc_world.js'),{startAway}=await import('./src/systems/life_context.js'),{ensureLocalContacts}=await import('./src/systems/remote_life.js'),{newRun,step}=await import('./src/testing/run.js'),{pendingDecision,playerChoices}=await import('./src/systems/player_decisions.js'),{saveWorkspace}=await import('./src/testing/feedback_store.js');
  const s=fixture({seed:61});initializePopulation(s);Object.assign(s.config,{content_enabled:false,decision_event_frequency:0,background_event_frequency:0,marriage_opportunity_frequency:0,npc_annual_marriage_rate:0,reproduction_frequency:0,illness_frequency:0,aging_loss:0});startAway(s,s.test.father_id,{duration:36});ensureLocalContacts(s,s.test.father_id);const r=newRun(s,'life','location-five-years'),end=s.current_world_month+60;
  const answer=()=>{while(pendingDecision(s)){const p=pendingDecision(s),choices=playerChoices(s,p).filter(x=>x.feasible),o=choices.find(x=>p.type==='away_review'&&x.id==='extend')||choices.find(x=>['skip','respect'].includes(x.id))||choices[0];step(r,{type:'player_choice',event_id:p.id,option_id:o.id});}};
  while(s.current_world_month<end){answer();step(r,{type:'month'});}answer();await saveWorkspace({runs:[r],active_run:r.run_id,feedback:[]});return {father:s.test.father_id,child:s.test.child_id,household:s.characters[s.test.child_id].current_household_id,followups:s.remote_life_threads[s.characters[s.test.father_id].remote_thread_id].followups.length};
 });}
 for(const width of[375,390,430]){
  await page.setViewportSize({width,height:844});const ids=await setup();await page.reload();await page.locator('.person-summary').waitFor();assert((await page.locator('.location-badge').innerText()).includes('家中'));assert(ids.followups>=8);assert(await page.locator('.timeline-year:not([open])').count()>=4);
  await page.locator('#summary .full-person>summary').click();await page.locator('#summary [data-person="'+ids.father+'"]').first().click();assert((await page.locator('#summary').innerText()).includes('外地'));assert((await page.locator('#summary .location-summary').innerText()).includes('工作'));assert((await page.locator('#summary .location-summary').innerText()).includes('24 / 36个月'));
  await page.locator('#summary .location-summary>details>summary').click();assert((await page.locator('#summary .location-summary').innerText()).includes('异地工作'));assert(await page.locator('#summary .remote-message').count()>=8);await page.locator('#summary [data-return-person]').first().click();
  await page.locator('#player-window>details>summary').click();await page.locator('#window-person').selectOption(ids.child);await page.locator('#window-direction').selectOption('relocation');await page.locator('#open-window').click();await page.locator('#choice-dialog[open]').waitFor();await page.locator('#choice-dialog [data-player-option="support"]').click();await page.locator('#choice-dialog').waitFor({state:'hidden'});
  assert((await page.locator('.location-badge').innerText()).includes('外地'));const facts=await page.evaluate(async()=>{const {readWorkspace}=await import('./src/testing/feedback_store.js'),{activeLocationContext,sameLocation}=await import('./src/systems/location_context.js');const s=(await readWorkspace()).runs[0].state;return {ref:activeLocationContext(s).ref,household:s.characters[s.test.child_id].current_household_id,same:sameLocation(s,s.test.child_id,s.test.father_id)};});assert.equal(facts.household,ids.household);assert(!facts.same);await page.reload();await page.locator('.location-badge').waitFor();assert((await page.locator('.location-badge').innerText()).includes('外地'));
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert(!overflow);const nav=(await page.locator('nav').boundingBox()).height;assert(nav<=60);const footer=await page.locator('.fixed-controls').boundingBox();assert(footer.height<90);await page.locator('#summary').scrollIntoViewIfNeeded();fs.mkdirSync('test-results',{recursive:true});await page.screenshot({path:'test-results/v240-'+width+'.png'});rows.push({width,overflow,nav_height:nav,months:60,remote_followups:ids.followups,remote_card:true,player_migration_clicked:true,household_unchanged:true,refresh_persisted:true});
 }
 assert.deepEqual(errors,[]);assert(requests.every(x=>!x.includes('/api/')));if(!process.env.TEST_URL)fs.writeFileSync('reports/v240-mobile.json',JSON.stringify({rows,errors,static_only:true},null,2)+'\n');console.log(JSON.stringify(rows));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
