import {entryResults,lifeHistoryView,summariesView,libraryShell,libraryRows} from './content_views.js';
import {characterCard,explainEntry,personName} from './presentation.js';
import {pendingDecision,playerChoices,windowAvailable} from '../systems/player_decisions.js';
import {META,TUNABLES,defaults,validateConfig,GOALS} from '../config/mock_tunables.js';
import {age,date,clone} from '../core/state.js';
import {fixture,CASES,COMBINATIONS} from '../testing/test_cases.js';
import {newRun,step,replay} from '../testing/run.js';
import {readWorkspace,saveWorkspace,feedbackFor,ISSUE_TYPES,exportEnvelope,validateImport} from '../testing/feedback_store.js';
import {geneticsBatch} from '../testing/genetics_lab.js';
import {ATTRIBUTES,scan,point,samples,healthChecks} from '../testing/behavior_lab.js';
import {marriageCandidates} from '../systems/marriage.js';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pretty=x=>'<pre>'+esc(JSON.stringify(x,null,2))+'</pre>';
let viewedPerson=null;let work,config=defaults(),running=false,stop=false,limit=36,issueIndex=null,lastPoint=null;
const run=()=>work.runs.find(r=>r.run_id===work.active_run),state=()=>run()?.state,cid=()=>state()?.control.current_control_character_id;
const status=(msg,error=false)=>{$('status').textContent=msg;$('status').className=error?'error':'';};
const wait=()=>new Promise(r=>setTimeout(r,0));
const persist=()=>saveWorkspace(work);
async function safe(fn){try{await fn();}catch(e){console.error(e);status(e.message,true);}}
function page(name){if(['behavior','genetics'].includes(name)&&run()&&run().mock_version!==META.mock_version){status('旧运行仅供查看与导出；请新建本版人物后使用实验室');return;}document.querySelectorAll('main>section').forEach(s=>s.hidden=s.id!==name);document.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-current',String(b.dataset.page===name)));if(name==='behavior'&&state())renderLab();if(name==='feedback')renderFeedback();}
const options=items=>items.map(([v,l])=>'<option value="'+esc(v)+'">'+esc(l)+'</option>').join('');
function name(id){const c=state()?.characters[id];return c?c.surname+c.given_name+' · '+age(state(),c)+'岁':id;}
function details(e,index){return entryResults(state(),e)+'<details><summary>为什么人物这样选择 / 查看原因</summary>'+explainEntry(state(),e)+'<details><summary>高级调试信息</summary>'+pretty(e)+'</details></details><div class="row feedback-buttons"><button data-rate="合理" data-index="'+index+'">合理</button><button data-rate="问题" data-index="'+index+'">记录问题</button><button data-rate="很好的结果" data-index="'+index+'">很好的结果</button></div>';}
function title(e){if(e.kind==='player_choice')return '【你的决定】'+(e.result.player_choice||'家庭安排');if(e.kind==='player_window')return '【你的决定】开启主动介入';if(e.kind!=='month')return ({marriage:'婚配安排：'+({married:'婚姻成立',refused:'本人拒绝',other_refused:'对方拒绝',delayed:'仍在议亲 / 拖延',blocked:'现实条件不满足',force_failed:'强制机会不足'}[e.result?.status]||e.result?.status||''),death:'死亡事实',succession:'玩家选择接班',inheritance:'个人遗产分配',enroll:'进入教育状态',employ:'进入职业状态',wish:'愿望完成',event:e.result?.event?.title})[e.kind]||e.kind;if(e.births?.length)return '新人物出生 · '+e.births.length+'名';const r=e.reports.find(r=>r.character_id===e.control_character_id)||e.reports[0];return r?.death?'人物死亡':r?.player_opportunity?.waiting?'需要你的决定 · '+r.player_opportunity.event.title:r?.decision?'【人物决定】'+r.decision.event.title:r?.background?.event?.title||r?.defaults?.primary?.name||'日常生活';}
function render(){const r=run(),s=state();$('run-select').innerHTML=options(work.runs.map(r=>[r.run_id,r.test_case_id+' · seed '+r.seed+' · '+date(r.state.current_world_month)]));$('run-select').value=work.active_run||'';
 if(!s){$('summary').innerHTML='<p>请从测试中心创建人物和家庭。</p>';return;}
 const c=s.characters[cid()],h=c&&s.households[c.current_household_id],j=c&&(s.careers[cid()]?.status==='active'?s.careers[cid()]:s.education[cid()]?.status==='active'?s.education[cid()]:null);
 const compatible=r.mock_version===META.mock_version;
 $('content-focus').value=s.test_focus_mode||'正常人生';$('focus-badge').textContent=s.test_focus_mode&&s.test_focus_mode!=='正常人生'?'TEST FOCUS MODE · '+s.test_focus_mode:'';
 $('life-history').innerHTML=lifeHistoryView(s,viewedPerson||cid(),$('history-domain').value);$('life-summaries').innerHTML=cid()?summariesView(s,viewedPerson||cid()):'';
 $('summary').innerHTML='<p class="badge">'+(s.world_id==='ancient'?'古代':'现代')+' · '+date(s.current_world_month)+' · seed '+r.seed+'</p>'+(compatible?characterCard(s,viewedPerson||cid(),cid()):'<h3>旧版本运行，只读保留</h3><p>请导出旧数据，并新建本版运行。旧结果不会被静默重算。</p>');
 $('player-window').innerHTML=compatible&&cid()?'<h3>玩家介入窗口</h3><p>'+ (windowAvailable(s)?'本次主动操作机会可用：选择方向与家庭成员。':'每'+s.config.player_window_months+'个月提供一次主动操作机会。')+'</p><label>支持谁<select id="window-person">'+options(Object.values(s.characters).filter(x=>x.alive&&x.current_household_id===c.current_household_id).map(x=>[x.character_id,name(x.character_id)]))+'</select></label><label>方向<select id="window-direction">'+options([['education','教育路线'],['career','职业支持 / 家庭事业'],['relocation','离乡发展'],['marriage','婚配安排'],['resource','家庭资源分配'],['care','长期照护与家庭分工']])+'</select></label><button id="open-window" '+(!windowAvailable(s)||pendingDecision(s)?'disabled':'')+'>提出家庭方向</button>':'';
 $('credits').textContent='强制机会 '+s.player.force_credits+' · 已完成愿望 '+s.player.fulfilled_wishes;$('pending').innerHTML=compatible?pendingHtml():'';
 const history=s.history.slice(-limit),offset=s.history.length-history.length,grouped=new Map();history.forEach((e,i)=>{const y=Math.floor(e.month/12);if(!grouped.has(y))grouped.set(y,[]);grouped.get(y).push({e,index:offset+i});});
 const card=({e,index})=>'<article class="card"><small>'+date(e.month)+'</small><h3>'+esc(title(e))+'</h3>'+details(e,index)+'</article>';
 $('timeline').innerHTML=[...grouped].reverse().map(([year,entries])=>{const ordered=entries.reverse(),important=ordered.filter(({e})=>e.kind!=='month'||e.births?.length||e.reports.some(r=>r.important)),ordinary=ordered.filter(x=>!important.includes(x));return '<details class="card" '+(year===Math.floor(s.current_world_month/12)?'open':'')+'><summary>'+year+'年 · '+entries.length+'条记录</summary>'+important.map(card).join('')+(ordinary.length?'<details><summary>普通月份 · '+ordinary.length+'个月</summary>'+ordinary.map(card).join('')+'</details>':'')+'</details>';}).join('')||'<p>推进一个月开始观察。</p>';$('older').hidden=s.history.length<=limit;
 $('marriage-target').innerHTML=options((c?marriageCandidates(s,cid()):[]).filter(x=>!x.reason).map(x=>[x.character_id,name(x.character_id)]));
 for(const [element,sex,key]of [['gen-father','男','father_id'],['gen-mother','女','mother_id']]){const el=$(element),value=el.value;el.innerHTML=options(Object.values(s.characters).filter(c=>c.sex===sex).map(c=>[c.character_id,name(c.character_id)]));el.value=s.characters[value]?value:s.test[key];}
 const filter=$('filter-case'),selected=filter.value;filter.innerHTML=options([['','全部案例'],...Object.keys(CASES).map(k=>[k,k]),['life','连续人生']]);filter.value=selected;
 document.querySelector('.fixed-controls').hidden=!!pendingDecision(s)||!compatible;document.querySelectorAll('[data-rate]').forEach(b=>b.disabled=!compatible);document.querySelectorAll('[data-months],#auto,#until-death,#next-generation').forEach(b=>b.disabled=running||!cid()||!compatible||!!pendingDecision(s));}
function pendingHtml(){const s=state(),e=pendingDecision(s);if(!e)return '';const labels={succession:'控制角色接班',inheritance:'主财产继承人',education:'教育方向支持',career:'职业发展支持',relocation:'离乡发展支持',marriage:'重点推动哪位婚配对象',force:'是否覆盖本人的当前拒绝',resource:'家庭资源分配',care:'家庭责任分配',conflict:'家庭危机与责任',health:'重大健康资源投入',away_review:'离乡期限结束后的支持'};return '<article class="card player-decision"><h3>需要你的决定</h3><p>'+esc(labels[e.type]||'家庭安排')+(e.character_id?' · '+esc(name(e.character_id)):'')+'</p><p>'+esc(e.payload.event?.title||'')+'</p><p>你决定家庭支持与资源安排；人物保留自己的反应。下列为预计立即影响，不预告未来随机结果。</p>'+playerChoices(s,e).map(o=>'<div class="card">'+(o.target_id?'<button data-person="'+o.target_id+'">查看'+esc(name(o.target_id))+'</button>':'')+'<button data-player-option="'+esc(o.id)+'" data-player-event="'+esc(e.id)+'" '+(!o.feasible?'disabled':'')+'>'+esc(o.label)+'</button><p>'+esc(o.impact)+'</p>'+(!o.feasible?'<p class="error">不可行：'+esc(o.reason)+'</p>':'')+'</div>').join('')+'</article>';}
function showChoices(){if(pendingDecision(state())){$('choice-content').innerHTML=pendingHtml();if(!$('choice-dialog').open)$('choice-dialog').showModal();}else $('choice-dialog').close();}
async function act(cmd){if(!run()||running)return;const e=step(run(),cmd);await persist();render();status('已执行并保存完整现场');showChoices();return e;}
async function advance(n,untilDeath=false){if(running||!cid())return;running=true;stop=false;render();const original=cid();let done=0;try{for(;done<n&&!stop;done++){if(!cid()||pendingDecision(state()))break;const entry=step(run(),{type:'month'});if($('play-style').value==='story'&&(entry.births.length||entry.reports.some(r=>r.character_id===cid()&&(r.background?.event||r.important)))){done++;break;}if(done%12===0){status('逐月运行 '+(done+1)+' / '+n);await persist();await wait();}if(untilDeath&&cid()!==original){done++;break;}}await persist();status('已逐月运行 '+done+'个月'+(untilDeath&&done===n&&cid()===original?'；达到 Mock 运行上限，人物仍存活。':'')+(pendingDecision(state())?'；需要你的决定，时间已暂停。':stop?'；已暂停。':''));}finally{running=false;render();}showChoices();}
function settings(){const val=id=>Number($(id).value);return {seed:val('seed')>>>0,world:$('world').value,template:$('template').value,resources:val('initial-resources'),health:val('initial-health'),stress:val('initial-stress'),attitude:val('initial-attitude'),config};}
async function startCase(case_id,mode='fixed'){if(running)return;const set=settings();if(!Number.isFinite(set.resources)||set.health<1||set.health>100||set.stress<0||set.stress>100||set.attitude<-100||set.attitude>100)throw Error('初始参数范围有误');viewedPerson=null;const s=fixture({...set,case_id}),r=newRun(s,mode,case_id);work.runs.push(r);work.active_run=r.run_id;await persist();render();page('simulation');const spec=CASES[case_id];if(pendingDecision(s)){showChoices();return;}if(!spec){if(case_id==='health')await advance(1);return;}
 const [,kind,value]=spec;if(kind==='months'||kind==='birth')await advance(value);else if(kind==='event')await act({type:'event',event_type:value});else if(kind==='death')await act({type:'death'});else if(kind==='marriage'||kind==='forced24'){const e=await act({type:'marriage',target_id:s.test.target_id,mode:kind==='forced24'?'force':value});if(kind==='forced24'){if(e.result.status==='married')await advance(24);else status('婚配结果 '+e.result.status+'；未伪造婚姻。可再次议亲或更换 seed 后观察24个月。');}}else if(kind==='genetics'||kind==='generations'){page('genetics');$('gen-count').value='20';$('gen-depth').value=kind==='generations'?'3':'1';renderGenetics();}}
function renderGenetics(){
 const layers=geneticsBatch(state(),$('gen-father').value,$('gen-mother').value,Number($('gen-count').value),Number($('gen-depth').value));
 const labels={intelligence:'智力',social:'社交',athletic:'运动',stress_resistance:'抗压',curiosity:'好奇心',height_basis:'身高基础',constitution:'体质',fertility_basis:'生育基础',hair_color_id:'发色',eye_color_id:'瞳色',skin_tone_id:'肤色',face_shape_id:'脸型',brow_shape_id:'眉形',eye_shape_id:'眼型',nose_shape_id:'鼻型',mouth_shape_id:'嘴型'};
 $('gen-result').innerHTML=layers.map(g=>'<div class="card"><h3>第'+g.generation+'代 · '+(g.healthy?'每个孩子至少3项直接继承，至多2项变异':'遗传约束错误')+'</h3><p>父系 '+g.sources.father+' / 母系 '+g.sources.mother+' / 变异 '+g.sources.mutation+'</p>'+
 Object.entries(g.continuous).map(([k,v])=>'<p>'+labels[k]+'：范围 '+v.min+'～'+v.max+'，均值 '+v.mean.toFixed(1)+'</p><progress value="'+v.mean+'" max="100"></progress>').join('')+
 Object.entries(g.colors).map(([k,counts])=>'<h3>'+labels[k]+'</h3>'+Object.entries(counts).map(([id,n])=>'<p>'+esc(id)+'：'+n+' / '+g.children.length+'</p><progress value="'+n+'" max="'+g.children.length+'"></progress>').join('')).join('')+
 g.children.map((c,i)=>'<details><summary>子代 '+(i+1)+' · 五官来源</summary>'+Object.entries(c.explanation.face).map(([k,v])=>'<p>'+labels[k]+'：'+({father:'父',mother:'母',mutation:'变异'})[v.source]+' · '+esc(v.value)+'</p>').join('')+'<details><summary>完整遗传解释与数值</summary>'+pretty(c)+'</details></details>').join('')+'</div>').join('');
}
function actionTable(actions){return '<table><tr><th>候选行为</th><th>概率</th></tr>'+actions.map(a=>'<tr><td>'+esc(a.action)+'</td><td>'+a.probability.toFixed(1)+'%</td></tr>').join('')+'</table>';}
function renderPoint(){if(!cid())return;const a=$('lab-attribute').value,v=a==='goal'?$('lab-goal').value:Number($('lab-value').value);$('lab-value-text').textContent=v;lastPoint=point(state(),cid(),$('lab-event').value,a,v);$('lab-point').innerHTML=actionTable(lastPoint.candidate_actions);$('lab-debug').textContent=JSON.stringify({input:lastPoint.context,actions:lastPoint.candidate_actions,excluded:lastPoint.excluded_actions},null,2);}
function renderLab(){if(!cid()){status('请先选择存活人物');return;}const rows=scan(state(),cid(),$('lab-event').value,$('lab-attribute').value);$('lab-health').innerHTML=healthChecks(rows).map(t=>'<p>'+esc(t)+'</p>').join('');const keys=[...new Set(rows.flatMap(r=>r.generated_actions.map(a=>a.action_id)))],names=Object.fromEntries(rows.flatMap(r=>r.generated_actions.map(a=>[a.action_id,a.action]))),colors=['#417856','#966236','#536ca0','#8b557d','#7d812b'];
 $('lab-table').innerHTML='<table><tr><th>属性</th>'+keys.map(k=>'<th>'+esc(names[k])+'</th>').join('')+'<th>合计</th></tr>'+rows.map(r=>'<tr><td>'+esc(r.value)+'</td>'+keys.map(k=>'<td>'+(r.candidate_actions.find(a=>a.action_id===k)?.probability||0).toFixed(1)+'%</td>').join('')+'<td>100%</td></tr>').join('')+'</table>';
 $('lab-chart').innerHTML='<svg viewBox="0 0 600 260" role="img" aria-label="行为概率曲线"><path d="M40 10 V220 H580" fill="none" stroke="#889"/><text x="2" y="20" font-size="12">100%</text><text x="8" y="222" font-size="12">0%</text>'+keys.map((k,i)=>'<polyline fill="none" stroke="'+colors[i%5]+'" stroke-width="2" points="'+rows.map((r,j)=>(40+j*530/(rows.length-1))+','+(220-(r.candidate_actions.find(a=>a.action_id===k)?.probability||0)*2)).join(' ')+'"/>').join('')+'<text x="40" y="245" font-size="12">0 / 第一类别</text><text x="480" y="245" font-size="12">100 / 最后类别</text></svg>'+keys.map((k,i)=>'<span style="color:'+colors[i%5]+'">'+esc(names[k])+'　</span>').join('');renderPoint();}
async function saveFeedback(kind,index,issue='',severity='',note=''){work.feedback.push(feedbackFor(run(),index,kind,issue,severity,note));await persist();status('已保存“'+kind+'”及完整现场');}
function renderFeedback(){const type=$('filter-type').value,ca=$('filter-case').value,ch=$('filter-character').value,sev=$('filter-severity').value;const rows=work.feedback.filter(f=>(!type||f.issue_type===type||f.feedback_type===type)&&(!ca||f.test_case_id===ca)&&(!ch||f.character_id?.includes(ch))&&(!sev||f.severity===sev));$('feedback-list').innerHTML=rows.slice().reverse().map(f=>'<article class="card"><h3>'+esc(f.feedback_type)+' · '+esc(f.issue_type||f.test_case_id)+'</h3><p>'+esc(f.severity)+' '+esc(f.note)+'</p><p>'+esc(f.character_id)+' · '+date(f.simulation_month)+' · seed '+f.seed+'</p><button data-replay="'+f.feedback_id+'">重放这个结果</button><button data-delete="'+f.feedback_id+'">删除单条</button><details><summary>原始现场</summary>'+pretty(f)+'</details></article>').join('')||'<p>暂无匹配反馈。</p>';}
function renderConfig(){$('config').innerHTML=Object.keys(TUNABLES).map(k=>'<label class="card">'+k+'<small>MOCK_TUNABLE</small><input data-config="'+k+'" value="'+esc(Array.isArray(config[k])?config[k].join(','):config[k])+'"></label>').join('');}
function download(filename,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function init(){work=await readWorkspace();config={...defaults(),...work.config};$('version').textContent='Mock Version '+META.mock_version+' · Design Version '+META.design_version;$('hash').textContent='Design SHA-256 '+META.design_sha256;$('case').innerHTML=options(Object.entries(CASES).map(([k,v])=>[k,k+' · '+v[0]]));$('combination').innerHTML=options(COMBINATIONS.map(([l,k],i)=>[i,l]));$('lab-attribute').innerHTML=options(Object.entries(ATTRIBUTES));$('lab-goal').innerHTML=options(GOALS.map(g=>[g,g]));$('issue-type').innerHTML=options(ISSUE_TYPES.map(t=>[t,t]));$('filter-type').innerHTML=options([['','全部类型'],['合理','合理'],['很好的结果','很好的结果'],...ISSUE_TYPES.map(t=>[t,t])] );renderConfig();render();if(!state())page('tests');status('已读取 '+work.runs.length+'个运行 / '+work.feedback.length+'条反馈');if(state()&&run().mock_version===META.mock_version)showChoices();}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;safe(async()=>{
 if(b.dataset.person){viewedPerson=b.dataset.person;$('choice-dialog').close();render();page('simulation');$('summary').scrollIntoView();return;}if(b.hasAttribute('data-return-person')){viewedPerson=null;render();return;}if(b.dataset.playerOption){await act({type:'player_choice',event_id:b.dataset.playerEvent,option_id:b.dataset.playerOption});return;}if(b.dataset.page)return page(b.dataset.page);if(b.id==='continue-life')return advance(12);if(b.id==='pause'){stop=true;return;}if(b.dataset.months)return advance(Number(b.dataset.months));
 if(b.dataset.rate){if(b.dataset.rate==='问题'){issueIndex=Number(b.dataset.index);$('issue-note').value='';$('feedback-dialog').showModal();}else await saveFeedback(b.dataset.rate,Number(b.dataset.index));return;}
 if(b.dataset.successor){await act({type:'succession',target_id:b.dataset.successor});$('choice-dialog').close();return;}
 if(b.dataset.heir){await act({type:'inheritance',deceased_id:b.dataset.deceased,target_id:b.dataset.heir});$('choice-dialog').close();return;}
 if(b.dataset.replay){const f=work.feedback.find(f=>f.feedback_id===b.dataset.replay),s=replay(f.replay,f.command_index),{command_index,...scene}=f.scene;status(JSON.stringify(s.history.at(-1))===JSON.stringify(scene)?'重放结果与保存现场一致':'重放现场不一致，请保留记录检查');$('feedback-list').insertAdjacentHTML('afterbegin','<details class="card"><summary>高级调试信息：重放结果</summary>'+pretty(s.history.at(-1))+'</details>');return;}
 if(b.dataset.delete){work.feedback=work.feedback.filter(f=>f.feedback_id!==b.dataset.delete);await persist();renderFeedback();return;}
 switch(b.id){
 case 'open-window':await act({type:'player_window',direction:$('window-direction').value,character_id:$('window-person').value});break;
 case 'new-life':await startCase('life','life');break;
 case 'run-case':await startCase($('case').value);break;
 case 'run-combination':await startCase(COMBINATIONS[Number($('combination').value)][1],'combined');break;
 case 'until-death':await advance(state().config.life_run_limit_months,true);break;
 case 'auto':await advance(state().config.life_run_limit_months);break;
 case 'next-generation':if(state().control.pending)showChoices();else await advance(12);break;
 case 'ordinary-marriage':case 'force-marriage':if(!$('marriage-target').value)throw Error('没有现实可行候选');await act({type:'marriage',target_id:$('marriage-target').value,mode:b.id==='force-marriage'?'force':'ordinary'});break;
 case 'intent-run':{const t=$('intent-event').value;await act({type:'event',event_type:t,target_id:t==='birth'?Object.values(state().marriages).find(m=>m.status==='active'&&m.people.includes(cid()))?.people.find(id=>id!==cid()):$('marriage-target').value||state().test.target_id,intervention:{mode:$('intent-mode').value,action_id:['career','relocation','birth'].includes(t)?'commit_terms':'try_lesson'}});break;}
 case 'wish':await act({type:'wish'});break;
 case 'enroll':await act({type:'enroll'});break;
 case 'employ':await act({type:'employ'});break;
 case 'test-death':if(confirm('确认在此测试运行中触发死亡？'))await act({type:'death'});break;
 case 'observe24':await advance(24);break;
 case 'older':limit+=36;render();break;
 case 'lab-scan':renderLab();break;
 case 'lab-sample':{if(!lastPoint)renderPoint();$('lab-sample').disabled=true;try{const rs=await samples(lastPoint.candidate_actions,Number($('lab-count').value),run().seed);$('lab-samples').innerHTML='<table><tr><th>行为</th><th>理论%</th><th>实际%</th><th>误差pp</th></tr>'+rs.map(r=>'<tr><td>'+esc(r.action)+'</td><td>'+r.theory.toFixed(2)+'</td><td>'+r.actual.toFixed(2)+'</td><td>'+r.error.toFixed(2)+'</td></tr>').join('')+'</table>';}finally{$('lab-sample').disabled=false;}break;}
 case 'gen-run':renderGenetics();break;
 case 'cancel-issue':$('feedback-dialog').close();break;
 case 'save-issue':await saveFeedback('问题',issueIndex,$('issue-type').value,$('issue-severity').value,$('issue-note').value);$('feedback-dialog').close();break;
 case 'close-choice':$('choice-dialog').close();break;
 case 'export-feedback':download('mock-v2-feedback.json',exportEnvelope({feedback:work.feedback}));break;
 case 'export-all':download('mock-v2-all.json',exportEnvelope({feedback:work.feedback,runs:work.runs,config}));break;
 case 'clear-feedback':if(confirm('清空全部反馈？请先导出。')&&confirm('再次确认删除此浏览器全部反馈？')){work.feedback=[];await persist();renderFeedback();}break;
 case 'save-config':{const next={};document.querySelectorAll('[data-config]').forEach(el=>next[el.dataset.config]=el.dataset.config==='face_mutation_count_weights'?el.value.split(',').map(Number):Number(el.value));config=validateConfig(next);work.config=config;await persist();status('参数已保存，仅新运行采用');break;}
 case 'reset-config':config=defaults();work.config=config;await persist();renderConfig();break;
 case 'export-config':download('mock-v2-config.json',exportEnvelope({source:'MOCK_TUNABLE',config}));break;
 }
 });});
$('run-select').addEventListener('change',()=>safe(async()=>{if(running)throw Error('请先暂停');work.active_run=$('run-select').value;viewedPerson=null;await persist();render();}));
$('lab-value').addEventListener('input',renderPoint);$('lab-goal').addEventListener('change',renderPoint);
for(const id of ['lab-event','lab-attribute'])$(id).addEventListener('change',()=>safe(renderLab));
for(const id of ['filter-type','filter-case','filter-character','filter-severity'])$(id).addEventListener('input',renderFeedback);
$('import').addEventListener('change',()=>safe(async()=>{const f=$('import').files[0];if(!f)return;if(f.size>100*1024*1024)throw Error('超过100MB，请分批导入');const d=validateImport(JSON.parse(await f.text())),merged={...work,feedback:[...work.feedback],runs:[...work.runs]};for(const f of d.feedback)if(!merged.feedback.some(x=>x.feedback_id===f.feedback_id))merged.feedback.push(f);for(const r of d.runs||[])if(!merged.runs.some(x=>x.run_id===r.run_id))merged.runs.push(r);if(!merged.active_run&&merged.runs.length)merged.active_run=merged.runs[0].run_id;await saveWorkspace(merged);work=merged;render();renderFeedback();status('导入完成，相同ID已去重');}));
$('library').innerHTML=libraryShell();$('library-results').innerHTML=libraryRows();
 document.querySelectorAll('[data-library-filter]').forEach(el=>el.addEventListener('change',()=>{$('library-results').innerHTML=libraryRows(...['domain','scale','feature'].map(k=>document.querySelector('[data-library-filter="'+k+'"]').value));}));
 $('history-domain').addEventListener('change',()=>{if(cid())$('life-history').innerHTML=lifeHistoryView(state(),viewedPerson||cid(),$('history-domain').value);});
 $('content-focus').addEventListener('change',()=>safe(async()=>{if(run())await act({type:'focus',value:$('content-focus').value});}));
 safe(init);
