import {playerDecisionType} from '../systems/player_decisions.js';
import {ANCIENT_EVENTS,CONTENT_DOMAINS} from '../content/ancient_events.js';
import {meaningfulEntries,fiveYearSummaries,changedFacts} from '../content/life_records.js';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=m=>Math.floor(m/12)+'年'+(m%12+1)+'月';
const name=(s,id)=>s.characters[id]?s.characters[id].surname+s.characters[id].given_name:id;
const value=x=>typeof x==='number'?Number(x.toFixed(2)):x;
export function changesView(s,before,after){const rows=changedFacts(before,after);return rows.length?'<h4>立即变化</h4><div class="fact-changes">'+rows.map(r=>{let label=r.name;for(const id of Object.keys(s.characters))label=label.replace(id,name(s,id));return '<p>'+esc(label)+' <strong>'+esc(value(r.before))+' → '+esc(value(r.after))+'</strong></p>';}).join('')+'</div>':'';}
export function resultView(s,d){
 if(!d)return '';const facts=d.content_result;
 const terms=facts?.after.long_term_states.filter(t=>t.status==='active'&&!facts.before.long_term_states.some(b=>b.id===t.id))||[];
 return '<article class="life-result"><h3>'+esc(d.event.title)+'</h3><p>'+esc(d.event.description)+'</p>'+(d.event.target_id?'<button data-person="'+esc(d.event.target_id)+'">查看相关人物 · '+esc(name(s,d.event.target_id))+'</button>':'')+'<p>'+ (d.event.decision_owner==='player'?'本次家庭安排：':'人物考虑过：')+d.candidate_actions.filter(a=>a.action_type!=='transition_action').map(a=>esc(a.action)).join('；')+'</p><p><strong>'+ (d.event.decision_owner==='player'?'你的资源安排':'人物最终决定')+'：</strong>'+esc(d.chosen_action)+'</p><h4>结果</h4><p>'+esc(facts?.outcome||d.actual_changes?.join('；')||'实际结果见下方记录')+'</p>'+(facts?changesView(s,facts.before,facts.after)+(facts.related_before?'<details><summary>相关人物的实际变化</summary>'+changesView(s,facts.related_before,facts.related_after)+'</details>':''):'')+(terms.length?'<h4>新的持续影响</h4>'+terms.map(t=>'<p>'+esc(t.default_behavior_effects.join('、'))+'</p>').join(''):'')+'</article>';
}
export function entryResults(s,e){const ds=e.kind==='month'?(e.reports||[]).filter(r=>r.character_id===e.control_character_id||r.important).flatMap(r=>[r.background?.decision,r.decision].filter(Boolean)):[e.result?.decision,...(e.result?.event?[e.result]:[])].filter(Boolean);const body=ds.map(d=>resultView(s,d)).join('');if(e.kind!=='month'&&e.before&&e.after&&!ds.some(d=>d.content_result))return body+'<h4>结果</h4><p>'+esc(e.result?.player_choice||e.result?.status||'已执行本次安排')+'</p>'+changesView(s,e.before,e.after);if(e.kind==='month'&&ds.some(d=>!d.content_result)){const r=e.reports.find(r=>r.character_id===e.control_character_id);return body+'<details><summary>本月合计变化（包含日常生活）</summary>'+changesView(s,r?.before,r?.after)+'</details>';}return body;}
export function lifeHistoryView(s,cid,filter='全部'){
 const rows=meaningfulEntries(s,cid).filter(e=>filter==='全部'||(filter==='玩家决定'?e.actor==='你的决定':({教育:/教育|学徒|技能/,职业:/职业|工作|谋生|事业/,家庭:/家庭|父母|子女|兄弟|育儿/,关系:/关系|邻里|朋友|社交/,婚姻:/婚|夫妻|生育/,健康:/健康|疾病|压力|疲劳|照护/,迁移:/迁移|离乡/}[filter]||/$a/).test(e.domain||'')));
 return rows.slice(-80).reverse().map(e=>'<p><small>'+date(e.month)+' · '+esc(e.actor)+'</small><br><strong>'+esc(e.title)+'</strong><br>'+esc(e.result)+(e.character_choice?'<br>人物反应：'+esc(e.character_choice):'')+'</p>').join('')||'<p>尚未发生此类重要经历。</p>';
}
export function summariesView(s,cid){return fiveYearSummaries(s,cid).map(g=>'<details><summary>'+g.age_from+'～'+g.age_to+'岁 · 五年回顾（仅真实日志）</summary><p>'+date(g.start)+'至'+date(g.end)+'，记录 '+g.entries.length+' 件经历；其中你的决定 '+g.player_decisions.length+' 次。</p>'+changesView(s,g.before,g.after)+'<h4>关键经历</h4>'+g.entries.filter(e=>e.actor==='你的决定'||e.details?.after?.long_term_states.length>e.details?.before?.long_term_states.length).slice(-12).map(e=>'<p>'+date(e.month)+' · '+esc(e.actor)+' · '+esc(e.title)+'：'+esc(e.result)+'</p>').join('')+'</details>').join('')||'<p>生活满五年后生成第一段回顾。</p>';}
export function libraryShell(){return '<h2>事件库 · 104个古代内容模板</h2><p>MOCK_EVENT_CONTENT · 发展主题与规模为两个维度；不按月份编排固定剧情。</p><div class="grid">'+[['domain','领域',['全部',...CONTENT_DOMAINS]],['scale','规模',['全部','daily','medium','major','发展型']],['feature','条件',['全部','人物自主','玩家决策','多阶段','真实 NPC','长期状态','持续问题']]].map(([id,label,values])=>'<label>'+label+'<select data-library-filter="'+id+'">'+values.map(v=>'<option value="'+esc(v)+'">'+esc(({daily:'日常',medium:'中型',major:'重大'})[v]||v)+'</option>').join('')+'</select></label>').join('')+'</div><div id="library-results"></div>';}
export function libraryRows(domain='全部',scale='全部',feature='全部'){return ANCIENT_EVENTS.filter(t=>(domain==='全部'||t.domain===domain)&&(scale==='全部'||scale==='发展型'&&t.developmental||t.importance===scale)&&(feature==='全部'||feature==='人物自主'&&!playerDecisionType({...t,content_template:true})||feature==='玩家决策'&&!!playerDecisionType({...t,content_template:true})||feature==='多阶段'&&t.transition_actions.length||feature==='真实 NPC'&&t.participant_requirements.real_person||feature==='长期状态'&&t.possible_long_term_states.length||feature==='持续问题'&&t.possible_ongoing_situations.length)).map(t=>'<details class="card"><summary>'+esc(t.display_templates.title)+' · '+esc(t.domain)+'</summary><p>'+esc(t.decision_goal)+'</p><p>触发：'+esc(t.trigger_conditions.condition)+'；最低年龄 '+t.trigger_conditions.min_age+'；历史/状态 '+esc(t.trigger_conditions.history_or_state||'无')+'</p><p>真实人物角色：'+esc(t.participant_requirements.role)+'</p><p>终局：'+t.terminal_outcomes.map(o=>esc(o.label)).join(' / ')+'</p><p>过程：'+(t.transition_actions.map(o=>esc(o.label)).join(' / ')||'无需多阶段')+'</p><p>影响：'+t.immediate_effect_types.map(esc).join('、')+'</p><p>后续：'+t.followup_tags.map(esc).join('、')+'；冷却 '+t.cooldown+'个月</p><details><summary>高级调试信息：完整模板</summary><pre>'+esc(JSON.stringify(t,null,2))+'</pre></details></details>').join('')||'<p>没有匹配的模板。</p>';}
