import {remoteMessages} from './location_views.js';
import {esc,personName} from './presentation.js';
import {date} from '../core/state.js';
import {populationStats} from '../systems/npc_world.js';
const num=x=>Number(x||0).toFixed(1);
export function pregnancyView(s,cid){const p=Object.values(s.reproduction).find(p=>p.status==='active'&&p.mother_id===cid);return p?'<p class="pregnancy-badge"><strong>怀孕 · 第'+(s.current_world_month-p.start_month+1)+'个月</strong> · 健康 '+num(s.health[cid].value)+' · 预计生产 '+date(p.due_month)+'</p>':'';}
export function noticeView(s,notices){return notices.map(n=>'<p class="pregnancy-notice"><strong>'+esc(({pregnancy:'【怀孕】',birth:'【生产】',birth_approaching:'【临近生产】',pregnancy_health:'【孕期健康提醒】'})[n.type]||'人生变化')+' '+esc(personName(s,n.mother_id))+'</strong> · 健康 '+num(n.health)+(n.type==='pregnancy'?' · 第1个月 · 预计 '+date(n.due_month)+'生产':'')+'</p>').join('');}
export function routineLines(r){const t=r?.routine?.tracks;if(!t)return [];const rows=[];if(t.career)rows.push('工作：'+t.career.name);if(t.education)rows.push('教育：'+t.education.name);if(t.family)rows.push('家庭：'+t.family.members+'人同地'+(t.family.remote_members?' · '+t.family.remote_members+'人异地':''));if(t.care)rows.push('照护：'+t.care.name);if(t.parenting)rows.push('育儿：'+t.parenting.young_children+'名幼儿 / '+t.parenting.children+'名子女');if(t.relationships)rows.push('关系：'+[...new Set(t.relationships.map(x=>x.kind))].join('、'));if(t.health&&(t.health.before!==t.health.after))rows.push('健康：'+num(t.health.before)+' → '+num(t.health.after));if(t.resources&&t.resources.before!==t.resources.after)rows.push('资源：本月净变化 '+num(t.resources.after-t.resources.before));if(t.pregnancy)rows.push('孕期：第'+t.pregnancy.month+'个月');if(t.long_term)rows.push('长期安排：'+t.long_term.active+'项继续推进');return rows;}
export function monthlyView(s,e){if(e.kind!=='month')return '';const r=e.reports.find(r=>r.character_id===e.control_character_id)||e.reports[0],lines=routineLines(r);return remoteMessages(s,e.remote_followups)+noticeView(s,e.notices||[])+(lines.length?'<div class="monthly-summary"><strong>本月生活</strong>'+lines.map(x=>'<p>'+esc(x)+'</p>').join('')+'</div>':'')+(e.remaining_events?'<p>同月还有 '+e.remaining_events+' 件待处理事件；完成玩家决定后点击继续。</p>':'')+e.reports.flatMap(r=>r.background?.routine?[r.background.routine]:[]).map(d=>'<details><summary>生活片段 · '+esc(d.event.title)+'</summary><p>'+esc(d.content_result?.outcome||d.chosen_action)+'</p></details>').join('');}
export function npcStatsView(s){const p=populationStats(s),group=(label,obj)=>'<p>'+label+'：'+Object.entries(obj).map(([k,v])=>esc(({active:'在读',completed:'已结业',paused:'暂缓',ended:'已结束',full:'完整模拟',simplified:'简化模拟',background:'背景维护'})[k]||k)+' '+v).join(' · ')+'</p>';return '<details><summary>NPC 世界统计 · 存活 '+p.alive+'人 / '+p.households+'户</summary><p>累计人口 '+p.total+' · 未婚适龄 '+p.unmarried_eligible+' · 已婚 '+p.married+'</p>'+group('年龄',p.age_groups)+group('职业',p.careers)+group('教育',p.education)+group('模拟精度',p.fidelity)+'<small>初始人口、姓名与重复抑制均为 MOCK_CONTENT / MOCK_TUNABLE。</small></details>';}
