import {LOCATION_LABELS,PURPOSE_LABELS} from '../systems/location_context.js';
import {META,validateConfig} from '../config/mock_tunables.js';
import {clone,age,snapshot} from '../core/state.js';
import {replay} from './run.js';
const DB='pea-mock-v2',STORE='workspace';
export async function database(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function readWorkspace(){const db=await database();try{return await new Promise((resolve,reject)=>{const t=db.transaction(STORE),r=t.objectStore(STORE).get('all');r.onsuccess=()=>resolve(r.result||{runs:[],feedback:[],active_run:null});r.onerror=()=>reject(r.error);});}finally{db.close();}}
export async function saveWorkspace(work){const db=await database();try{await new Promise((resolve,reject)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put(work,'all');t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||Error('本地保存中止，请导出数据'));});}finally{db.close();}}
export const ISSUE_TYPES=['事件不该发生 / 时机不对','默认行为不合理','现实条件判断有问题','性格 / 兴趣 / 人生目标表现不合理','选择可以发生，但概率感觉不对','状态更新错误','前后逻辑矛盾','跨系统影响错误','太重复 / 太机械','文本表现有问题','其他 / 说不上来'];
export function feedbackFor(run,index,kind,issue='',severity='',note=''){
 // Reconstruct the historical month instead of capturing today's character state.
 const entry=run.state.history[index];if(!entry)throw Error('找不到历史现场');
 const report=entry.reports?.find(r=>r.character_id===(entry.control_character_id||run.initial_state.control.current_control_character_id))||entry.reports?.[0]||entry;
 const recordedBefore=report.before||entry.before,recordedAfter=report.after||entry.after;
 const character_id=recordedBefore?.character?.character_id||recordedAfter?.character?.character_id;
 const previous=replay(run,entry.command_index-1),current=replay(run,entry.command_index);
 const before=character_id?snapshot(previous,character_id):null,after=character_id?snapshot(current,character_id):null,c=before?.character||after?.character;
 const decision=report.decision||entry.result?.decision||entry.result?.arrangement?.child||entry.result?.child||entry.result||{};
 return {...META,feedback_id:crypto.randomUUID(),created_at:new Date().toISOString(),test_mode:run.test_mode,test_case_id:run.test_case_id,run_id:run.run_id,character_id:c?.character_id||null,world_id:run.state.world_id,simulation_month:entry.month,character_age:before?.character_age??after?.character_age,seed:run.seed,current_household_id:c?.current_household_id,lineage_id:c?.lineage_id,character_snapshot:clone(c||null),scene:clone(entry),state_before:clone(before),state_after:clone(after),defaults:clone(report.defaults||null),event:clone(decision.event||null),candidate_actions:clone(decision.candidate_actions||[]),filtered_actions:clone(decision.excluded_actions||[]),sampling:clone(decision.sampling||null),systems:clone(report.systems||entry.result?.systems||[]),diff:clone(report.diff||entry.diff||[]),probability_input:clone(decision.context||null),event_tags:clone(decision.event?.tags||[]),player_intervention:clone(decision.intervention||(entry.kind==='player_choice'?entry.result:null)||entry.result?.force||null),final_behavior:entry.result?.status||decision.chosen_action||report.defaults?.primary?.name||entry.kind,feedback_type:kind,issue_type:issue,severity,note,command_index:entry.command_index,replay:{...META,seed:run.seed,initial_state:clone(run.initial_state),commands:clone(run.commands.slice(0,entry.command_index+1))}};
}
export function exportEnvelope(data){return {...META,export_time:new Date().toISOString(),...data};}
export function validateImport(d){if(![2,3,4].includes(d.schema_version)||!Array.isArray(d.feedback))throw Error('需要 V2 反馈 JSON / 全部测试数据 JSON');const check=(f)=>{if(!f.feedback_id||!f.replay?.initial_state||!Array.isArray(f.replay.commands)||!f.scene||!Number.isInteger(f.command_index))throw Error('反馈缺少完整可重放现场');if(f.schema_version>=3)validateState(f.replay.initial_state);if(f.replay.commands.length>20000)throw Error('重放命令数量过大');for(const cmd of f.replay.commands)if(!['month','event','marriage','death','succession','inheritance','wish','enroll','employ','player_window','player_choice'].includes(cmd.type))throw Error('不支持的重放命令');};d.feedback.forEach(check);if(d.runs)for(const run of d.runs){if(run.schema_version>=3){validateState(run.state);validateState(run.initial_state);}if(!run.run_id||!Array.isArray(run.commands))throw Error('运行记录不完整');}return d;}
export function validateState(s){if(!s||!['ancient','modern'].includes(s.world_id)||!Number.isInteger(s.current_world_month)||!s.characters||!s.households||!s.resources||!s.control||!s.ongoing_situations||!s.recent_history||!Array.isArray(s.player_decision_events)||!Array.isArray(s.marriage_proposal_history))throw Error('存档状态不完整');validateConfig(s.config);for(const c of Object.values(s.characters)){if(!c.character_id||typeof c.alive!=='boolean'||!s.health[c.character_id]||!s.resources.personal[c.character_id]||!s.households[c.current_household_id])throw Error('人物引用无效');if(c.current_location_context&&(!LOCATION_LABELS[c.current_location_context]||!PURPOSE_LABELS[c.location_purpose]||typeof c.location_context_ref!=='string'||!Number.isInteger(c.location_start_month)||c.expected_location_duration!==null&&(!Number.isInteger(c.expected_location_duration)||c.expected_location_duration<1)))throw Error('地点状态无效');for(const group of [c.talents,c.personality,c.dynamic])if(!group||Object.values(group).some(v=>!Number.isFinite(v)||v<0||v>100))throw Error('人物数值不合法');if(!['skin_01','skin_02','skin_03','skin_04'].includes(c.appearance?.skin_tone_id))throw Error('肤色 ID 无效');}return s;}
