import {bound} from '../core/rng.js';
import {learn} from './education_career.js';
export function defaultBehaviors(s,cid){const c=s.characters[cid];if(!c?.alive||!c.active_simulation)return {primary:null,secondary:[],conflict:false,time_used:0,work_fraction:0};const h=s.health[cid],cfg=s.config;let list=[];if(h.value<30)list.push({type:'rest',name:'因健康限制休养',time:.8,priority:100});else{const e=s.education[cid],j=s.careers[cid];if(e?.status==='active')list.push({type:'education',name:e.name,time:e.time,priority:80,skill:e.skill});if(j?.status==='active')list.push({type:'career',name:j.name,time:j.time,priority:80,skill:j.skill});}
 const household=s.households[c.current_household_id],care=household?.responsibilities[cid];if(care?.until>s.current_world_month)list.push({type:'care',name:'家庭照护',time:cfg.care_time,priority:90});
 for(const t of Object.values(s.long_term_states).filter(t=>t.character_id===cid&&t.status==='active'&&!t.source))if(t.default_behavior_effects.some(x=>['减少外出','减少共同活动'].includes(x)))list.push({type:'recovery',name:'安排后的休息与适应',time:.15,priority:t.priority});
 if(!list.length)list.push({type:'daily',name:'维持日常生活',time:.4,priority:10});
 list.sort((a,b)=>b.priority-a.priority);const capacity=h.value<30?.85:1;let used=0;const planned=list.map(a=>{const allocated=Math.max(0,Math.min(a.time,capacity-used));used+=allocated;return {...a,allocated};});return {primary:planned[0],secondary:planned.slice(1),conflict:list.reduce((v,a)=>v+a.time,0)>capacity,time_used:used,work_fraction:(planned.find(a=>a.type==='career')?.allocated||0)/(list.find(a=>a.type==='career')?.time||1)};
}
export function executeDefaults(s,cid,d){const c=s.characters[cid];for(const a of [d.primary,...d.secondary].filter(Boolean)){if(a.skill&&a.allocated>0){const growth=s.config.skill_growth*a.allocated*(.5+(c.talents.intelligence+c.talents.curiosity)/200);learn(s,cid,a.skill,growth);s[a.type==='career'?'careers':'education'][cid].progress+=a.allocated;if(a.type==='education'&&s.education[cid].progress>=s.education[cid].duration*s.config.education_progress_fraction){s.education[cid].status='completed';c.experiences.push({month:s.current_world_month,type:'education_completed'});}}}
 c.dynamic.fatigue=bound(c.dynamic.fatigue+d.time_used*s.config.default_work_fatigue-s.config.fatigue_recovery);c.dynamic.stress=bound(c.dynamic.stress-s.config.stress_recovery+(d.conflict?s.config.conflict_stress:0));c.dynamic.mood=bound(c.dynamic.mood+Math.sign(s.config.rest_mood_target-c.dynamic.mood)*s.config.mood_recovery);
}
