import {age} from '../core/state.js';
export const parentsAt=(c,month)=>[...c.biological_parent_ids,...c.adoptive_parent_ids.filter(id=>c.adoption_records.some(r=>r.parent_id===id&&r.month<=month))];
export function childrenAt(s,cid,month){return Object.values(s.characters).filter(c=>parentsAt(c,month).includes(cid));}
export function successors(s,cid){const death=s.characters[cid].death_month??s.current_world_month;let frontier=[cid],direct=[];const seen=new Set(frontier);for(let depth=1;depth<=3;depth++){frontier=frontier.flatMap(id=>childrenAt(s,id,death)).filter(c=>!seen.has(c.character_id)).map(c=>c.character_id);frontier.forEach(id=>seen.add(id));direct.push(...frontier.filter(id=>s.characters[id].alive).map(id=>({character_id:id,priority:'direct',depth})));}if(direct.length)return direct;
 // MOCK interpretation of two collateral generations: siblings and their children.
 const parents=parentsAt(s.characters[cid],death);const siblings=Object.values(s.characters).filter(c=>c.character_id!==cid&&parentsAt(c,death).some(id=>parents.includes(id)));return [...new Set([...siblings.map(c=>c.character_id),...siblings.flatMap(c=>childrenAt(s,c.character_id,death).map(x=>x.character_id))])].filter(id=>s.characters[id].alive).map(id=>({character_id:id,priority:'collateral'}));}
export function queueSuccession(s,cid){const candidates=successors(s,cid);s.control.current_control_character_id=null;s.control.pending={deceased_id:cid,candidates};s.control.ended=!candidates.length;return candidates;}
export function selectSuccessor(s,cid){if(!s.control.pending?.candidates.some(x=>x.character_id===cid)||!s.characters[cid]?.alive)throw Error('请选择有效接班候选');s.control.current_control_character_id=cid;s.control.pending=null;s.control.ended=false;}
export function queueInheritance(s,cid){const c=s.characters[cid],eligible=childrenAt(s,cid,c.death_month).filter(x=>x.alive).map(x=>x.character_id);s.inheritances[cid]={deceased_id:cid,eligible,status:eligible.length?'awaiting_player':'waiting_future_rules',death_month:c.death_month};}
export function inheritEstate(s,cid,main){const p=s.inheritances[cid];if(!p||p.status!=='awaiting_player'||!p.eligible.includes(main))throw Error('无有效遗产分配请求或主继承人');const estate=s.resources.personal[cid].personal_inheritable_estate;const cents=Math.round(estate*100),alloc={};if(p.eligible.length===1)alloc[main]=cents;else{alloc[main]=Math.round(cents*.6);const others=p.eligible.filter(id=>id!==main),rest=cents-alloc[main],base=Math.floor(rest/others.length);others.forEach((id,i)=>alloc[id]=base+(i<rest%others.length?1:0));}for(const [id,value]of Object.entries(alloc))s.resources.personal[id].personal_inheritable_estate+=value/100;s.resources.personal[cid].personal_inheritable_estate=0;p.status='completed';p.main=main;p.distribution=Object.fromEntries(Object.entries(alloc).map(([id,v])=>[id,v/100]));return p;}
